name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
      - '.github/workflows/docs.yml'

jobs:
  check-docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material pymdown-extensions
    
    - name: Check documentation builds
      run: |
        # Create basic mkdocs.yml if it doesn't exist
        if [ ! -f mkdocs.yml ]; then
          cat > mkdocs.yml << EOF
        site_name: Astrabot Documentation
        site_description: Personal AI fine-tuning from Signal conversations
        repo_url: https://github.com/yourusername/astrabot
        
        theme:
          name: material
          features:
            - navigation.sections
            - navigation.expand
            - toc.integrate
        
        nav:
          - Home: README.md
          - Tutorials:
              - Getting Started: tutorials/getting-started.md
          - How-To Guides:
              - Process Signal Backup: how-to/process-signal-backup.md
          - Reference:
              - API:
                  - TrainingDataCreator: reference/api/training-data-creator.md
        
        markdown_extensions:
          - pymdownx.highlight
          - pymdownx.superfences
          - admonition
          - toc:
              permalink: true
        EOF
        fi
        
        # Test that docs build successfully
        mkdocs build --strict
    
    - name: Check for broken links
      run: |
        pip install linkchecker
        linkchecker docs/ --no-warnings || true